export let Brands=[
    {
        id:1,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1650454451/pq9kpnup8oubjoihzhmw.jpg",
        name:"Tata 1mg Blood Pressure Monitor Fully Automatic",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"Healthcare Devices",
        type:"device",
        price:1540,
        discount:5,
        rating:4.4,
        quantity:"box of 1 unit",
        description:["Fully automatic with upper arm style ","Measures blood pressure and pulse rate ","Encompasses the feature of hypertension detector","Can be used with a USB cable as well as with batteries. ","Stores 90 Sets of memory for 2 users simultaneously.","Highly accurate with +/- 3mmHg accuracy range ","Has a large LCD display and date and time indicator as well","Automatic power off after 3 mins if left idle","Measures the pressure on inflation, which reduces the uncomfortable feeling "]

    },
    {
        id:2,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1642507775/gmkrpf1imjj9djwvq4gq.jpg",
        name:"Tata 1mg Multivitamin Supreme, Zinc, Calcium and Vitamin D Immunity Booster Capsule",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"vitamins & nutritions",
        type:"vitamin",
        price:995,
        discount:55,
        rating:4.1,
        quantity:"bottle of 60 capsules",
        description:["Helps to strengthen the immune system","Helps to improve physical fitness and strength","Useful in improving memory and concentration","Provides essential fatty acids such as EPA & DHA","Supports healthy functioning of the cardiovascular system","Enriched with multivitamins, multi-minerals, probiotics, ginseng and omega 3 fatty acids"]
    },
    {
        id:3,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1653505842/sunqcfmxhmpwx32hnewh.jpg",
        name:"Tata 1mg Digital Thermometer",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"Healthcare & Devices",
        type:"Device",
        price:105,
        discount:4,
        rating:3.9,
        quantity:"box of 1 unit",
        description:["Accurate measurement within 20 seconds","Non-mercury based (100% safe)t","Auto switch off with memory function ","Easy to read LED display ","Dual-mode measurement in °F & °C","Completion alarm","Can be used in the oral cavity, rectal cavity, or under the armpit"]
    },
    {
        id:4,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1653939234/wtnvztvks8lsai4rezdz.jpg",
        name:"Tata 1mg Cotton Crepe Bandage 8cm",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"Healthcare Devices",
        type:"supports & braces",
        price:160,
        discount:30,
        rating:4.7,
        quantity:"box of 1 Crepe bandage",
        description:["It relieves muscle strain and joint pain","It reduces swelling and provides warmth and firm support to the affected area","These bandages come in 3 sizes: S (6 cm), M (8 cm) and L (10 cm) with fastening clips","It is made from super-soft, skin-friendly and absorbent material"]
    },
    {
        id:5,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1637324194/gc3u9gfc331wtsipnljl.jpg",
        name:"Tata 1mg Calcium + Vitamin D3, Zinc, Magnesium and Alfalfa Tablets for Joint Health & Immunity",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"vitamins & nutritions",
        type:"vitamin",
        price:595,
        discount:50,
        rating:4.2,
        quantity:"bottle of 60 tablets",
        description:["Helps in maintaining healthy bones and teeth","Strengthens the immune system","Reduces the risk of Osteoporosis and Rickets","Helps in preventing calcium deficiency and improves the bio-availability of calcium ","Aids in improving the absorption of Calcium in the body","Promotes flexibility and mobility of joints","Contains Calcium (Calcium citrate maleate 2000 mg), Vitamin D3, Zinc, Magnesium vitamins & minerals "]
    },
    {
        id:6,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1653939711/fleyk9fp2twf2ztnwbcb.jpg",
        name:"Tata 1mg Probiotics 30 Billion CFUs+ Capsule with Prebiotic Fibre",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"vitamins & nutritions",
        type:"vitamin",
        price:595,
        discount:50,
        rating:4.8,
        quantity:"box of 60 capsules",
        description:["Contains 30 billion CFU plus with 14 live probiotic strains and prebiotic fibre","These capsules enhance the immune system","Helps in relieving gas and bloating","Non-GMO and no added preservatives"]
    },
    {
        id:7,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1642507827/fwram2p7rbkoigjg6zas.jpg",
        name:"Tata 1mg Salmon Omega 3 Fish Oil Capsule",
        from:"Tata 1mg Healthcare Solutins Private Limited",
        images:[],
        brand:"",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:995,
        discount:55,
        rating:4.4,
        quantity:"box of 60 capsules",
        description:["Helps in improving cardiovascular health","Can aid in boosting memory","Supports healthy functioning of the brain","Helps in regulating cholesterol levels and high blood pressure","Supports flexibility and mobility of joints","Helps reduce inflammation ","Rich in omega 3 fatty acids EPA and DHA"]
    }
]