export let Brands=[
    {
        id:1,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1651517851/cf2lveoml6p1co0yegcb.jpg",
        name:"Ensure Chocolate Powder Refill",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:620,
        discount:5,
        rating:4.5,
        quantity:"box of 400 gb Powder",
        description:["Provides balanced and complete nutrition","Helps to toughen the bones","Strengthens the immune system","Helps to maintain a healthy digestive system","Helps to stimulate metabolism","Promotes energy level","Helps to maintain the electrolyte level"]

    },
    {
        id:2,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1651517893/bo2vufgnqrj1quemeh1u.jpg",
        name:"Ensure Vanilla Powder Refill",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:1250,
        discount:6,
        rating:4.5,
        quantity:"box of 1 kg Powder",
        description:["Provides balanced and complete nutrition","Helps to toughen the bones","Strengthens the immune system","Helps to maintain a healthy digestive system","Helps to stimulate metabolism","Promotes energy level","Helps to maintain the electrolyte level"]
    },
    {
        id:3,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1647510044/mrqm83ag4gzuvxbphena.jpg",
        name:"Ensure Diabetes Care Vanilla Delight Powder",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:725,
        discount:3,
        rating:4.5,
        quantity:"jar of 400 gm powder",
        description:["Helps to manage blood glucose levels","Supports weight management","Helps build muscle mass","Contains high-quality protein and sucralose"]
    },
    {
        id:4,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1647510477/p2mxlcvf8sltcoub6x0a.jpg",
        name:"Ensure Diabetes Care Vanilla Delight Powder",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:1555,
        discount:5,
        rating:4.5,
        quantity:"box of 1 kg powder",
        description:["Helps to manage blood glucose levels","Supports weight management","Helps build muscle mass","Contains high-quality protein and sucralose"]
    },
    {
        id:5,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1655231559/rzk6dsfxjzr2cwnjrdlp.jpg",
        name:"Ensure Plus Vanilla Powder",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:1375,
        discount:8,
        rating:4.5,
        quantity:"jar of 1 kg powder",
        description:["Adult nutritional drink","Strengthens the immune system","Can be used either as tube feed or as oral feed","It supports patient's recovery","Increases both the caloric and protein intake","Contains FOS, a prebiotic fibre"]
    },
    {
        id:6,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1628101697/tselpy0wtgy9wa0z8ons.jpg",
        name:"PediaSure Kids Nutrition Drink with Arginine & Natural Vitamin K2 Vanilla Delight for 2+",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:760,
        discount:10,
        rating:4.5,
        quantity:"box of 1 kg powder",
        description:["Comes in 3 delectable flavours of premium chocolate, vanilla delight and Kesar badam","Formulated with 37 nutrients to help support growth","Boosts immune function and brain development","Helps improve immunity and gives visible growth in 90 days"]
    },
    {
        id:7,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1628101607/orfyvvjd1nkaoyimmgzf.jpg",
        name:"PediaSure Kids Nutrition Drink with Arginine & Natural Vitamin K2 Vanilla Delight for 2+",
        from:"Abbott Healthcare PrivateLimited",
        images:[],
        brand:"",
        catogery:"nutrition",
        type:"",
        price:1375,
        discount:7,
        rating:4.5,
        quantity:"box of 1 kg powder",
        description:["Comes in 3 delectable flavours of premium chocolate, vanilla delight and Kesar badam","Formulated with 37 nutrients to help support growth","Boosts immune function and brain development","Helps improve immunity and gives visible growth in 90 days"]
    }
]