export let Brands=[
    {
        id:1,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1653420127/bwjc62pjckssjtrpgqib.jpg",
        name:"Dabur Pure Herbs Immunity Booster Ashwagandha Tablet",
        from:"Dabur India Ltd",
        images:[],
        brand:"Dabur",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:175,
        discount:20,
        rating:4.3,
        quantity:"bottle of 60 tablets",
        description:["Excellent immune-boosting effects on the immune system","Helps one to improve strength and stamina by improving heart and lung capacity while increasing energy levels","Dabur Ashwagandha has shown an adaptogenic effect that helps fight physical and mental stress and improve general well-being"]

    },
    {
        id:2,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1611742468/cvp4h2fk4ci2sn9fvi60.jpg",
        name:"1mg Ashwagandha Pure Natural Extract 500mg Capsule",
        from:"Tata 1mg Healthcare Solutions Private",
        images:[],
        brand:"Tata",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:495,
        discount:50,
        rating:4.3,
        quantity:"bottle of 60 capsules",
        description:["Helps in relieving stress","Enhances strength and stamina","Helps enhance vigour and vitality","Nourishes the nervous and immune system"]
    },
    {
        id:3,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1600162191/cropped/wtc6iza2awdhx0nxvkhr.jpg",
        name:"Sri Sri Tattva Ashwagandha 500mg Tablet",
        from:"Sriveda Sattva Pvt Ltd",
        images:[],
        brand:"Ashwagandha",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:150,
        discount:10,
        rating:4.3,
        quantity:"bottle of 60 tabletes",
        description:["Promotes quality sleep","Helps in managing stress and anxiety","Restores energy and strength","Helps to delay premature ageing"]
    },
    {
        id:4,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1600198005/cropped/nmoetxpxliyjcdl2ufy1.jpg",
        name:"Dabur Ashwagandhadi Lehya",
        from:"Dabur India Ltd",
        images:[],
        brand:"Dabur",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:400,
        discount:7,
        rating:4.5,
        quantity:"jar of 400 gm Paste",
        description:["A herbal revitalising tonic","Provides energy and fights fatigue","May help to improve sexual stamina"]
    },
    {
        id:5,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1617883255/ctozmetqi5o053dnidh6.jpg",
        name:"Jiva Ashwagandha Tablet",
        from:"Jiya Ayurvedic Pharmacy Ltd",
        images:[],
        brand:"Jiya",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:240,
        discount:17,
        rating:4.3,
        quantity:"bottle of 120 tablets",
        description:["Strengthens the nervous system","Helps to relieve stress and feeling of anxiety","Improves immunity and strength of the body"]
    },
    {
        id:6,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1633868568/qtuwledvtpqcg30gmkfz.jpg",
        name:"Baidyanath Vansaar Ashwagandha Tablet",
        from:"Shree Baidyanath Ayurved Bhawan Pvt Ltd",
        images:[],
        brand:"Baidyanath",
        catogery:"ayurved",
        type:"nutrition",
        price:169,
        discount:17,
        rating:4.0,
        quantity:"box of 60 tablets",
        description:["Helps the body to handle life’s daily emotional and physical stress","Ashwagandha is known to support getting good sleep at night","Helps fight symptoms of anxiety and depression"]
    },
    {
        id:7,
        img:"https://onemg.gumlet.io/image/upload/a_ignore,w_380,h_380,c_fit,q_auto,f_auto/v1650263994/gq3yhaapl0zf0h4wknqv.jpg",
        name:"Organic India Ashwagandha Veg Capsule",
        from:"Organic India",
        images:[],
        brand:"Ashwagandha",
        catogery:"vitamins & nutritions",
        type:"nutrition",
        price:205,
        discount:20,
        rating:4.4,
        quantity:"box of 60 vegicaps",
        description:["A natural dietary supplement to treat low energy states and exhaustion","Protects against infections, cold and flu","Helps in relieving mental, physical and emotional stress","Helps build sexual and reproductive balance"]
    }
]